/**
 * Generate README.md - Human-readable quick start
 * Short, direct, plain English
 */
export function generateReadme(projectName: string): string {
  return `# ${projectName}

Blueprint generated by [Sketch2Prompt](https://sketch2prompt.com)

## How to Use

1. Copy these files to your project root
2. Open \`START.md\` in your AI assistant (Cursor, Claude Code, Windsurf, etc.)
3. Follow the prompts — the AI will confirm your setup and generate IDE-specific instructions

## Files

| File | Purpose |
|------|---------|
| \`START.md\` | **Give this to your AI first** — initialization protocol |
| \`PROJECT_RULES.md\` | System architecture, constraints, build order |
| \`AGENT_PROTOCOL.md\` | Workflow rules, code standards, library policy |
| \`specs/*.md\` | Component specifications (AI loads these as needed) |
| \`diagram.json\` | Re-import into Sketch2Prompt to edit your diagram |

## What Happens

Your AI assistant will:
1. Read the blueprint files
2. Ask you to confirm the setup
3. Generate an IDE-specific instruction file (\`.cursorrules\`, \`CLAUDE.md\`, etc.)
4. Begin implementation following the build order

---

*Need to make changes? Import \`diagram.json\` back into [Sketch2Prompt](https://sketch2prompt.com)*
`
}
