import type { DiagramNode } from '../../types'

/**
 * Aggregate unique tech stacks from all nodes
 */
function aggregateTechStacks(nodes: DiagramNode[]): string[] {
  const stacks = new Set<string>()
  nodes.forEach((node) => {
    const techStack = node.data.meta.techStack ?? []
    techStack.forEach((tech) => {
      if (tech) stacks.add(tech.trim())
    })
  })
  return Array.from(stacks).sort()
}

/**
 * Get component type summary
 */
function getTypeSummary(nodes: DiagramNode[]): string {
  const typeCounts: Record<string, number> = {}
  nodes.forEach((node) => {
    const type = node.data.type
    typeCounts[type] = (typeCounts[type] ?? 0) + 1
  })
  return Object.entries(typeCounts)
    .map(([type, count]) => `${count} ${type}`)
    .join(', ')
}

/**
 * Get component list with types
 */
function getComponentList(nodes: DiagramNode[]): string {
  return nodes
    .map((node) => `- **${node.data.label}** (${node.data.type})`)
    .join('\n')
}

/**
 * Generate START.md bootstrap file
 * This file guides the downstream AI through confirmation and IDE setup
 */
export function generateStartMd(
  nodes: DiagramNode[],
  projectName: string
): string {
  const techStacks = aggregateTechStacks(nodes)
  const techStackSummary = techStacks.length > 0
    ? techStacks.join(', ')
    : 'Not specified'
  const typeSummary = getTypeSummary(nodes)
  const componentList = getComponentList(nodes)

  return `# Welcome to ${projectName}

This blueprint was generated by [Sketch2Prompt](https://github.com/jmassengille/sketch2prompt). Before you begin implementation, let's confirm the setup and configure your environment.

---

## Quick Summary

**Project:** ${projectName}
**Components:** ${String(nodes.length)} (${typeSummary})
**Tech Stack:** ${techStackSummary}

### Components
${componentList}

### Key Constraints (from AGENT_PROTOCOL.md)
- **Minimalism First:** Start simple, scale when necessary — no enterprise patterns without explicit request
- **Security Baseline:** Validate inputs at boundaries, never hardcode secrets, structured error logging
- **Modularity:** Functions max 50 lines, files max 300 lines, max 3 nesting levels

---

## Your Blueprint Files

| File | Purpose | When to Read |
|------|---------|--------------|
| \`PROJECT_RULES.md\` | System constitution, architecture constraints | **Read FIRST** before any implementation |
| \`AGENT_PROTOCOL.md\` | Workflow guidance, code standards, library policy | Read before starting work |
| \`specs/*.yaml\` | Component specifications with responsibilities | Load **only** the active component |
| \`diagram.json\` | Re-import into Sketch2Prompt if needed | Only for editing the diagram |

---

## Step 1: Confirm Understanding

Please read \`PROJECT_RULES.md\` and \`AGENT_PROTOCOL.md\`, then confirm:

1. Does the component structure match your intent?
2. Are the tech stack choices correct?
3. Any constraints you want to adjust?

**Reply with "confirmed" to proceed, or describe what needs adjustment.**

---

## Step 2: IDE Setup

Once confirmed, I'll generate your IDE-specific instruction file.

**Which IDE or AI assistant are you using?**

| Option | Generated File | Description |
|--------|----------------|-------------|
| **Claude Code** | \`CLAUDE.md\` | Claude Code CLI instructions |
| **Cursor** | \`.cursorrules\` | Cursor AI rules file |
| **Windsurf** | \`.windsurfrules\` | Windsurf rules file |
| **GitHub Copilot** | \`.github/copilot-instructions.md\` | Copilot custom instructions |
| **Other/Generic** | \`AI_INSTRUCTIONS.md\` | Universal AI assistant instructions |

**Reply with your IDE choice** (e.g., "Claude Code", "Cursor", etc.)

---

## What Happens Next

After confirmation and IDE selection, I will:

1. **Index** all blueprint files to understand the full system
2. **Generate** your IDE-specific instruction file with:
   - Project-specific rules from \`PROJECT_RULES.md\`
   - Workflow guidance from \`AGENT_PROTOCOL.md\`
   - Component registry and build order
3. **Create** \`STATUS.md\` to track implementation progress
4. **Begin** implementation following the build order in \`PROJECT_RULES.md\`

---

## IDE Instruction Template

When you confirm your IDE choice, use this template structure to generate the instruction file:

\`\`\`markdown
# [Project Name]

## System Overview
[From PROJECT_RULES.md Section 1]

## Architecture Constraints
[From PROJECT_RULES.md Section 3 - ALWAYS/NEVER/PREFER]

## Code Standards
[From PROJECT_RULES.md Section 4 - stack-specific rules]

## Component Registry
[Table from PROJECT_RULES.md Section 2]

## Build Order
[From PROJECT_RULES.md Section 5]

## Workflow
[From AGENT_PROTOCOL.md - Index → Plan → Implement → Verify]

## Library Policy
[From AGENT_PROTOCOL.md - search before building, minimalism mandate]
\`\`\`

Adapt formatting to match the specific IDE's conventions.

---

*Generated by Sketch2Prompt — helping humans define systems so AI can stop guessing.*
`
}
